### ISSUE TITLE
In app QR scan delayed (red box around QR before form loads)

### ISSUE THREAD

**Issue by DylanHobbs** [TrapScan/TrapScan-prod#10]

**Comment by KurtisPapple** [comment]
Working now but very delayed. need to make instant form load upon QR recognition like v1 app

**Comment by DylanHobbs** [comment]
So I'm still not sure which delay you mean.

Is it the highlighted QR is on the screen too long? 

Or the transition between the camera portion closing and the form opening?

It'd be a different solution depending on this.

**Comment by KurtisPapple** [comment]
> So I'm still not sure which delay you mean.
> 
> Is it the highlighted QR is on the screen too long? 
> 
> Or the transition between the camera portion closing and the form opening?
> 
> It'd be a different solution depending on this.

Here is a video of what I see, note the red box around QR for a few seconds before form loads https://photos.app.goo.gl/ha2JZstoeSgpe97d8
