### ISSUE TITLE
🔎Search component 🔁 Make enter submit first result

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan-prod#18]
### Group by function -------------------

- [x] 1) **Add Group by function, so that we can display any field and group by one other field. **For example show traps in search results, grouped by the project they are in. Or can reuse component in future for something like, search for Scans, grouped by what Trap they are for. Or Search for Catches, grouped by what Species caught. Or search for Users, grouped by Project they belong to
- [x] 2) **Group by style**:
font-family: Fira Sans;
font-size: 15px;
font-weight: 400;
line-height: 18px;
letter-spacing: 0.01em;
text-align: left;
padding: 16px 0px 8px 4px;
Dark mode text colour: `t_blue_gray-300`
Light mode text colour: `t_blue_gray-700`

_Should result in look and spacing between text and buttons like this:_
![image](https://user-images.githubusercontent.com/80499565/202868764-1c271d5a-76f2-4f90-a70d-f8ecf0f21102.png)

### Functional fixes -------------------

When searching for a Trap after scanning an QR that isn't linked (Link QR):
- [x] 3) **Green header bar needs to display the unique QR ID, like in the scan form** (currently it says "Map QR")
- [x] 4) **Add the following Text above the search bar so people know what is happening and what they need to do** (Fira Sans Regular 18px and Semi Bold 24px)
> This QR card needs to be linked to a Trap to activate it

> **Select a Trap**

![image](https://user-images.githubusercontent.com/80499565/202833460-e9d87695-4c13-4812-bb2c-1a8c411a823a.png)

### Style fixes -------------------

Dark mode:

- [x] 5) **Drop down background should be `t_black-850`**
- [x] 6) **Border should be `t_blue_gray-700`**
- [x] 7) **First item highlight should be `t_purple-300`**

![Image](https://user-images.githubusercontent.com/80499565/202832081-3b2dc388-0865-48ca-ba92-3833251dbe12.png)

Light mode:

- [x] 8) **Border should be `t_blue_gray-300`**

- [ ] 9) **Character match highlights:** Typeface should be Medium weight and `t_blue_gray-400`** (for both themes) and change to Bold weight and "full colour" only for the characters that match the input (like image below)
  - [ ] 10) **Light mode text match "full colour" (the default text colour): `t_black-800`**
  - [ ] 11) **Dark mode text match "full colour" (the default text colour): `t_white-200`**

![Image](https://user-images.githubusercontent.com/80499565/202831422-62ed44b2-c070-4eb2-8f11-22ad5f7d1b6a.png)

-----

- [x] 12) **There should be no background colour for the icons** (Currently there is small 24px darker colour behind them like big selector buttons have

![Image](https://user-images.githubusercontent.com/80499565/202832307-18a33624-e3f8-4ad3-99cb-fb087f76afb4.png)

----

When Searching for TRAPs:

- [x] 13) **Typeface should be Fira Sans instead of Montserrat** (Fira Sans should be default search result font, Montserrat only use for when QR Cards are the results. Fira Sans is more compact, so easier to fit all characters of larger names like projects. But Montserrat needed for QRs so easier to recognise as that is typeface on QR cards)
- [x] 14) **the Trap icon should be used instead of the QR icon**

![Image](https://user-images.githubusercontent.com/80499565/202832035-dc2fd27e-234e-4fd0-962b-ddba87453389.png)
 

- [x] 15) **Search drop down top borders should be zero** (see red used to highlight where it should be squared)
![Image](https://user-images.githubusercontent.com/80499565/202831291-8bbfa238-a51d-43ad-8407-3c19aaa8d5da.png)

When Searching for QRs:

- [x] 16) **QR names should have first letter capitalized**, so if I search for "vu", I will see "Vuw-1", _not_  "vuw-1". Like this:

![Image](https://user-images.githubusercontent.com/80499565/202878634-8e002735-119e-46d7-b8ab-de68a048186d.png)

**Comment by KurtisPapple** [comment]
@apolol 

 3) Green header bar needs to display the unique QR ID, like in the scan form (currently it says "Map QR")

**Can this please have first letter only as capital letter? Right now the QR name displays as ALL CAPITALS, should be like everywhere else with first letter Capital only**

 **For these ones below, do you want me to split into a later ticket as enhancement, or do you want to finish it now?**

- [ ] 9) Character match highlights: Typeface should be Medium weight and t_blue_gray-400** (for both themes) and change to Bold weight and "full colour" only for the characters that match the input (like image below)

 10) Light mode text match "full colour" (the default text colour): t_black-800

 11) Dark mode text match "full colour" (the default text colour): t_white-200

- [ ]  13) Typeface should be Fira Sans instead of Montserrat (Fira Sans should be default search result font, Montserrat only use for when QR Cards are the results. Fira Sans is more compact, so easier to fit all characters of larger names like projects. But Montserrat needed for QRs so easier to recognise as that is typeface on QR cards)

**Comment by KurtisPapple** [comment]
@apolol Enter button to submit first result still not working on Mobile or Desktop. If this possible to fix?

**Comment by apolol** [comment]
@KurtisPapple It`s work only on PC.

**Comment by KurtisPapple** [comment]
@apolol and no way to make it work on mobile at all?
