### ISSUE TITLE
Cannot install new QRs (freezes app)

### ISSUE THREAD

**Issue by KurtisPapple** [TrapScan/TrapScan-prod#8]
**When Installing a new QR (trap_id = null)**, clicking the picklist freezes the app and you have to restart

AC

1) Clicking on drop down does not freeze app
2) Typing will filter list down to options that match what you have typed for far

Video showing this bug and Re-map bug (#13)
https://photos.app.goo.gl/UDsuMuec892HRssb7

**Comment by DylanHobbs** [comment]
https://github.com/TrapScan/TrapScan-prod/pull/11

**Comment by KurtisPapple** [comment]
@DylanHobbs eta on #11 ? 

If more than a week then we need to fix current version so new QRs can be mapped, as I'm about to start mailing new QRs out to multiple projects 😬
